---

- hosts: mac
  roles:
    - role: mac
      tags: mac
  vars_prompt:
    - name: MAS_LOGIN
      prompt: "Mac App Store user name"
    - name: MAS_PASSWORD
      prompt: "Mac App Store password"
      private: True
  vars_files:
    - mac_vars.yml


- hosts: dev
  roles:
    - role: development
      tags: development
  vars_files:
    - mac_vars.yml


- hosts: mercy
  roles:
    - role: mercy
      tags: mercy
  vars_files:
    - mac_vars.yml


- hosts: centurylink
  roles:
    - role: centurylink
      tags: centurylink
  vars_files:
    - mac_vars.yml
