---

# Mac OS X 10.15 comes with ZSH 5.7, and uses it as the default shell for new accounts.

- name: Set 'current_shell' to path of current shell
  shell: "dscl . -read ~ UserShell | sed 's/UserShell: //'"
  register: current_shell
  changed_when: false

- name: Use ZSH as login shell
  command: "chsh -s /bin/zsh {{ ansible_user }}"
  become: yes
  when: "current_shell.stdout != ('/bin/zsh')"
